# Redirect all paths to index.html for SPA, excluding static assets
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false

# Cache JavaScript files for better performance
[[headers]]
  for = "/js/*"
  [headers.values]
    Cache-Control = "max-age=31536000, immutable"

# Cache CSS files for better performance
[[headers]]
  for = "/css/*"
  [headers.values]
    Cache-Control = "max-age=31536000, immutable"

# Cache image files for better performance
[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "max-age=31536000, immutable"

# Explicitly exclude static assets from being redirected to index.html
[[redirects]]
  from = "/js/*"
  to = "/js/:splat"
  status = 200

[[redirects]]
  from = "/css/*"
  to = "/css/:splat"
  status = 200

[[redirects]]
  from = "/images/*"
  to = "/images/:splat"
  status = 200
